(function () {
    var fonts = app.fonts.allFonts;
    var fontFamilies = [];
    var done = {};
    for (var _i = 0, fonts_1 = fonts; _i < fonts_1.length; _i++) {
        var font = fonts_1[_i];
        var familyName = font[0].familyName;
        if (done[familyName]) {
            continue;
        }
        done[familyName] = true;
        fontFamilies.push("    \"".concat(font[0].familyName, "\" = \"").concat(font[0].familyName, "\","));
    }
    var template = "// generated by generateFontFamilyTypeDefs.jsx\n\ndeclare const enum _FontFamily {\n{{FONT_FAMILIES}}\n}\n";
    var outputFile = new File("".concat(new File($.fileName).parent.parent.absoluteURI, "/typings/fontFamily.gen.d.ts"));
    outputFile.encoding = "utf-8";
    if (outputFile.open("w")) {
        outputFile.write(template.replace("{{FONT_FAMILIES}}", fontFamilies.join("\n")));
        outputFile.close();
    }
})();
